[package]
name = "op_sys"
version = "0.1.0"
edition = "2024"


[dependencies]
bootloader = "0.9"
volatile = "0.2.7"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.10.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"